### ISSUE TITLE
Filtering Timepunches should give an error when filtering for timepunches from users that dont exist

### ISSUE THREAD

**Issue by phurpatshering79** [nycrecords/timeclock#12]
If I filter for TimePunches requested by a user/email not in the database, I should get an error informing me that the user/email does not exist in the database.

**Comment by MunifNagi** [comment]
I think this issue has been already resolved, when trying to filter for TimePunches requested by a user/email not in the database, it gives an error saying "Invalid Email"

**Comment by joelbcastillo** [comment]
@MunifNagi  - Can you confirm that this is complete? Provide a screenshot and then we can close this out.

**Comment by MunifNagi** [comment]
<img width="1198" alt="Screen Shot 2020-03-20 at 6 13 59 PM" src="https://user-images.githubusercontent.com/46773316/77210161-a7dc4e00-6ad6-11ea-8c79-fcd9fb9585b8.png">
@joelbcastillo
