### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by phurpatshering79** [nycrecords/timeclock#8]
User received Internal Server Error when clicking Submit Request.

**Comment by joelbcastillo** [comment]
@phurpatshering79 - Was this from the Jira backlog or something you noticed? 

If the latter, see if you can provide more details so that we can come up with a way to fix it.

**Comment by phurpatshering79** [comment]
@joelbcastillo  Yes, this was from the Jira backlog. I am not sure how to best move ahead with this as the detail is limited.
